# Generated by Django 3.2.25 on 2024-05-26 21:58

from django.db import migrations, models
import django.db.models.deletion
import places.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم المعلان بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم المعلان بالانجلزي')),
                ('end_time', models.DateTimeField(validators=[places.models.check_date_time], verbose_name='نهائية العرض')),
                ('image', models.ImageField(upload_to='images/advertising', verbose_name='صورة الاعلان')),
                ('type_advertising', models.IntegerField(choices=[(1, 'الرئيسي'), (2, 'الفرعي')], default=1, verbose_name='نوع الاعلان')),
                ('urls_ar', models.URLField(blank=True, null=True, verbose_name='الرابط الذي يكون داخل الصورة بالغة العربية')),
                ('urls_en', models.URLField(blank=True, null=True, verbose_name='الرابط الذي داخل الصورة بالغة الانجلزية')),
                ('status', models.IntegerField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, verbose_name='الحالة')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'الاعلان',
                'verbose_name_plural': 'الاعلانات',
            },
        ),
        migrations.CreateModel(
            name='AreWe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_ar', models.TextField(verbose_name='الهدف بالعربي')),
                ('goal_en', models.TextField(blank=True, null=True, verbose_name='الهدف بالانجلزي')),
                ('image_goal', models.ImageField(upload_to='images/arewe', verbose_name='صورة الهدف')),
                ('message_ar', models.TextField(verbose_name='الرسالة بالعربي')),
                ('message_en', models.TextField(blank=True, null=True, verbose_name='الرسالة بالانجلزي')),
                ('image_message', models.ImageField(upload_to='images/arewe', verbose_name='صورة الرسالة')),
                ('idea_ar', models.TextField(verbose_name='الفكرة بالعربي')),
                ('idea_en', models.TextField(blank=True, null=True, verbose_name='الفكرة بالانجلزي')),
                ('image_idea', models.ImageField(upload_to='images/arewe', verbose_name='صورة الفكرة')),
                ('vision_ar', models.TextField(verbose_name='الرؤية بالعربي')),
                ('vision_en', models.TextField(blank=True, null=True, verbose_name='الرؤية بالانجلزي')),
                ('image_vision', models.ImageField(upload_to='images/arewe', verbose_name='صورة الرؤية')),
                ('status', models.IntegerField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, verbose_name='الحالة')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'من نحن',
                'verbose_name_plural': 'من نحن',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم البلاد بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم البلاد بالانجلزي')),
                ('status', models.IntegerField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, verbose_name='الحالة')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'البلاد',
                'verbose_name_plural': 'البلدان',
            },
        ),
        migrations.CreateModel(
            name='Provinec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم الماحفظة بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم المحافظة بالانجلزي')),
                ('status', models.IntegerField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, verbose_name='الحالة')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.country', verbose_name='البلاد')),
            ],
            options={
                'verbose_name': 'المحافظة',
                'verbose_name_plural': 'المحافظات',
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم المديرية بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم المديرية بالانجلزي')),
                ('status', models.IntegerField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, verbose_name='الحالة')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('provinec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.provinec', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'المديرية',
                'verbose_name_plural': 'المدريات',
            },
        ),
    ]
