# Generated by Django 3.2.25 on 2024-06-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
       # ('accounts', '0003_auto_20240608_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم العملة بالعربي ')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم العملة بالانجلزي')),
                ('cut_ar', models.CharField(max_length=50, verbose_name='اختصار العملة بالعربي')),
                ('status', models.ImageField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, upload_to='', verbose_name='حالة العرض')),
                ('cut_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='اختصار العملة بالانجلزي')),
                ('icon', models.ImageField(upload_to='image/currency', verbose_name='رمز العملة')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'نوع العملة',
                'verbose_name_plural': 'أنواع العملة',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ar', models.ImageField(upload_to='images/offer', verbose_name='الصورة صورة غلاف العرض بالعربي')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='image/offer', verbose_name='الصورة غلاف العرض بالانجلزي')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم العرض بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم العرض بالانجلزي')),
                ('description_ar', models.TextField(verbose_name='الوصف بالعربي')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='الوصف بالانجلزي')),
                ('status', models.ImageField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, upload_to='', verbose_name='حالة العرض')),
                ('duration', models.DateTimeField(verbose_name='تاريخ انتهاء العرض')),
                ('price_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر قبل')),
                ('price_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر قبل')),
                ('distinct', models.BooleanField(default=False, verbose_name='هل العرض مميز')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.currencytype', verbose_name='نوع العملة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='القسم')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.market', verbose_name='المحل التجاري')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.website', verbose_name='الموقع الالكتوني')),
            ],
            options={
                'verbose_name': 'العرض والخصومات',
                'verbose_name_plural': 'العروض والخصومات',
            },
        ),
        migrations.CreateModel(
            name='LocalCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ar', models.ImageField(upload_to='images/coupon', verbose_name='الصورة بالعربي')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='images/coupon', verbose_name='الصورة بالانجلزي')),
                ('coupon_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الكوبون')),
                ('status', models.ImageField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, upload_to='', verbose_name='حالة الكوبون')),
                ('description_ar', models.TextField(verbose_name='نبذة عن الكوبو ن بالعربي')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='نبذة عن الكوبون بالانجلزي')),
                ('terms_of_use_ar', models.TextField(verbose_name='شروط الاستخدام في بالعربي')),
                ('terms_of_use_en', models.TextField(blank=True, null=True, verbose_name='شروط الاستخدام بالانجلزي')),
                ('use', models.IntegerField(verbose_name='عدد الاستخدام ')),
                ('duration', models.DateTimeField(verbose_name='تاريخ انتهاء القسيمة')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.currencytype', verbose_name='نوع العملة')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.market', verbose_name='المحل التجاري')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.website', verbose_name='الموقع الالكتوني')),
            ],
            options={
                'verbose_name': 'القسائم المحلية',
                'verbose_name_plural': 'القسائم المحلية',
            },
        ),
        migrations.CreateModel(
            name='GlobalCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ar', models.ImageField(upload_to='images/coupon', verbose_name='الصورة بالعربي')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='images/coupon', verbose_name='الصورة بالانجلزي')),
                ('coupon_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الكوبون')),
                ('status', models.ImageField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, upload_to='', verbose_name='حالة الكوبون')),
                ('description_ar', models.TextField(verbose_name='نبذة عن الكوبو ن بالعربي')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='نبذة عن الكوبون بالانجلزي')),
                ('terms_of_use_ar', models.TextField(verbose_name='شروط الاستخدام في بالعربي')),
                ('terms_of_use_en', models.TextField(blank=True, null=True, verbose_name='شروط الاستخدام بالانجلزي')),
                ('use', models.IntegerField(verbose_name='عدد الاستخدام ')),
                ('duration', models.DateTimeField(verbose_name='تاريخ انتهاء القسيمة')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.currencytype', verbose_name='نوع العملة')),
                ('global_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.globalwebsite', verbose_name='الموقع الالكتروني')),
            ],
            options={
                'verbose_name': 'الكوبون العالمي',
                'verbose_name_plural': 'الكوبون العالمي',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(max_length=50, verbose_name='الاسم بالانجلزي')),
                ('image_ar', models.ImageField(upload_to='images/coupon', verbose_name='الصورة بالعربي')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='images/coupon', verbose_name='الصورة بالانجلزي')),
                ('status', models.ImageField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, upload_to='', verbose_name='حالة القسيمة')),
                ('coupon_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة القسية')),
                ('description_ar', models.TextField(verbose_name='نبذة عن القسيمة بالعربي')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='نبذة عن القسية بالانجلزي')),
                ('terms_of_use_ar', models.TextField(verbose_name='شروط الاستخدام في بالعربي')),
                ('terms_of_use_en', models.TextField(blank=True, null=True, verbose_name='شروط الاستخدام بالانجلزي')),
                ('duration', models.DateTimeField(verbose_name='تاريخ انتهاء القسيمة')),
                ('use', models.IntegerField(verbose_name='عدد الاستخدام ')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.currencytype', verbose_name='نوع العملة')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.market', verbose_name='المحل التجاري')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.website', verbose_name='الموقع الالكتوني')),
            ],
            options={
                'verbose_name': 'القسيمة',
                'verbose_name_plural': 'القسائم',
            },
        ),
    ]
