# Generated by Django 3.2.25 on 2024-05-27 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('places', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ar', models.ImageField(upload_to='images/webite', verbose_name='صورة الموقع بالعربي')),
                ('image_en', models.ImageField(blank=True, upload_to='images/webite', verbose_name='صورة الموقع بالانجليزي')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم الموقع الاكترني بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='اسم الموقع الاكتروني بالانجلزي')),
                ('about_the_site_ar', models.TextField(verbose_name='نبذة عن الموقع الاكتروني بالعربي')),
                ('about_the_site_en', models.TextField(blank=True, verbose_name='نبذة عن الموقع الاكتروني بالانجلزي')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الاكتروني')),
                ('link', models.URLField(verbose_name='رابط الموقع')),
                ('status', models.IntegerField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, verbose_name='حالة الموقع')),
                ('facebook', models.URLField(blank=True, verbose_name='رابط الفيسبوك')),
                ('the_x', models.URLField(blank=True, verbose_name='منصة اكس')),
                ('instagram', models.URLField(blank=True, verbose_name='انستقرام')),
                ('tiktok', models.URLField(blank=True, verbose_name='منصة تكتك')),
                ('whatsapp', models.URLField(blank=True, verbose_name='واتساب')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدام المنشاء')),
                ('departments', models.ManyToManyField(to='department.Department', verbose_name='مجلات الموقع الاكتروني')),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.directorate', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'الموقع الالكتروني ',
                'verbose_name_plural': 'المواقع الالكتروني',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ar', models.ImageField(upload_to='images/webite', verbose_name='الصورة الموقع بالعربي')),
                ('image_en', models.ImageField(blank=True, upload_to='images/webite', verbose_name='صورة الموقع بالانجلزي')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم المحل التجاري بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='اسم المحل التجاري بالانجزي')),
                ('about_the_market_ar', models.TextField(verbose_name='نبذة عن المحل التجاري بالعربي')),
                ('about_the_market_en', models.TextField(blank=True, verbose_name='نبذة المحل التجاري بالانجلزي')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الاكتروني')),
                ('link', models.URLField(blank=True, verbose_name='رابط الموقع')),
                ('status', models.IntegerField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, verbose_name='حالة المحل التجاري')),
                ('facebook', models.URLField(blank=True, verbose_name='رابط الفيسبوك')),
                ('the_x', models.URLField(blank=True, verbose_name='منصة اكس')),
                ('instagram', models.URLField(blank=True, verbose_name='انستقرام')),
                ('tiktok', models.URLField(blank=True, verbose_name='منصة تكتك')),
                ('whatsapp', models.URLField(blank=True, verbose_name='واتساب')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدام المنشاء')),
                ('departments', models.ManyToManyField(to='department.Department', verbose_name='مجلات المحل التجاري')),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.directorate', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'محل تجاري',
                'verbose_name_plural': 'محلات تجاريه',
            },
        ),
    ]
