# Generated by Django 3.2.25 on 2024-06-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_market_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم الموقع بالعربي')),
                ('name_en', models.CharField(max_length=50, verbose_name='اسم الموقع بالانجلزي')),
                ('status', models.IntegerField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, verbose_name='حالة المحل التجاري')),
                ('link', models.URLField(verbose_name='رابط الموقع')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'الموقع العالمي',
                'verbose_name_plural': 'المواقع العالمية',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=-2022, verbose_name='تاريخ الانشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='market',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=-2022, verbose_name='تاريخ الانشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='website',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=-2022, verbose_name='تاريخ الانشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
    ]
