# Generated by Django 3.2.25 on 2024-05-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم القسم بالعربي')),
                ('name_en', models.CharField(max_length=50, verbose_name='اسم القسم بالانجلزي')),
                ('status', models.IntegerField(choices=[(1, 'قيد الانشاء'), (2, 'تم الانشاء'), (3, 'تم التوقيف')], default=2, verbose_name='حالة القسم')),
                ('image', models.ImageField(upload_to='images/department', verbose_name='الصورة')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الاقسام',
            },
        ),
    ]
